@startuml

component "Web Application" #LightSteelBlue

component "Search/Recommandation engine" #LightSteelBlue

node "Order management" #LightSteelBlue {
    [Borrowing]
    [Returning]
    [SAV]
}

component "Shopping cart" #LightSteelBlue

component "Delivery management" #LightSteelBlue

node "Catalog" #LightSteelBlue {
    [catalog management]
    [inventory management]
    [Accounting]
}

component "Profile" #LightSteelBlue

component "Identity" #LightSteelBlue

"Web Application" --> Catalog
"Web Application" --> Profile
"Web Application" --> Identity
"Web Application" --> "Search/Recommandation engine"
"Web Application" --> "Shopping cart"
"Web Application" --> "Order management"
Catalog --> "Search/Recommandation engine"
"Search/Recommandation engine" --> Profile
"Order management" --> Catalog
"Order management" --> "Delivery management"
Profile --> Identity

@enduml